hydra:
  run:
    dir: .

defaults:
  - _self_
  - model: bilstm_bert

random_seed: 42

data:
  batch_size: 32
  num_workers: 4

  preprocessed_dir: ./preprocessed_data/CSJ/ver220109_word

  fp_list: ./corpus/CSJ/fp.list

train:
  out_dir: exp/CSJ/ver220110

  loss_weights: True

  model_type: group       # {non_personalized, group}
  group_id: 1                        # id of group, if model is group
  
  fine_tune: True
  resume: False
  load_ckpt_step: 59999

  gpus: 1
  auto_select_gpus: True
  max_steps: 20000
  check_val_every_n_epoch: 5
  gradient_clip_val: 0.5

  optim:
    optimizer:
      name: Adam
      params:
        lr: 1.0e-05
    lr_scheduler:
      name: StepLR
      params:
        step_size: 100000
        gamma: 0.1

  checkpoint:
    params:
      dirname: ckpt
      monitor: val_loss
      every_n_train_steps: 10000
      save_top_k: -1

  logging:
    name: log
    version: ver