hydra:
  run:
    dir: .

random_seed: 42
n_jobs: 8

data:
  batch_size: 32
  num_workers: 4
    
eval:
  exp_dir: exp/CSJ/ver220110
  out_dir: predicted_data/CSJ/ver220110

  model_type: group       # {non_personalized, group}
  group_id: 1                        # id of group, if model is group

  loss_weights: True

  gpus: 1
  auto_select_gpus: True

  checkpoint:
    step: 9999
