hydra:
  run:
    dir: /media/yuta_matsunaga/Matsunaga_disk_1/disfluency/grouping_prediction-lrec2022/prediction/yamazaki2020_bilstm

random_seed: 42
n_jobs: 8

data:
  batch_size: 32
  num_workers: 4

  in_feat_dir: ./preprocessed_data/CSJ/ver211207_1/infeats
  out_feat_dir: ./preprocessed_data/CSJ/ver211207_1/outfeats

  eval:
    utt_list: preprocessed_data/CSJ/ver211018_1_cross_val/dev_all_cv4.list
    fp_rate_list: preprocessed_data/CSJ/ver211018_1_cross_val/dev_all_cv4_filler_rate_list.txt

  fp_list: corpus/CSJ/fp_list.txt
    
eval:
  default_root_dir: exp/CSJ/ver211018_1_cross_val/weighted_loss/cv4
  out_dir: predicted_data/CSJ/ver211018_1_cross_val/weighted_loss/cv4

  each_speaker: True

  loss_weights: True

  gpus: 1
  auto_select_gpus: True

  checkpoint:
    step: 59999
