hydra:
  run:
    dir: .

random_seed: 42
n_jobs: 10

out_dir: ./preprocessed_data/CSJ/ver220109_word

# get feature
bert_model_dir: ./bert/Japanese_L-24_H-1024_A-16_E-30_BPE_WWM_transformers
fp_list_path: ./corpus/CSJ/fp.list