hydra:
  run:
    dir: /media/yuta_matsunaga/Matsunaga_disk_1/disfluency/grouping_prediction-lrec2022/prediction/git_predict_filledpauses_groups

random_seed: 42
n_jobs: 10

speaker_list_path: ./corpus/CSJ/speaker_koen.list
corpus_dir: ./corpus/CSJ
out_dir: ./preprocessed_data/CSJ/ver220109_word
person_id_list_path: ./corpus/CSJ/speaker.list

# tagtext
# thresh_len: 0
# tokenizer_name: juman              # support (sudachipy, juman)

# split data
group_list_path: ./corpus/CSJ/core_person_class_by_word_list.txt

# get feature
# nlp_model: bert                 # support (bert, fasttext)
# fasttext_dir: ./fastText
# fasttext_dim: 300
bert_model_dir: ./bert/Japanese_L-24_H-1024_A-16_E-30_BPE_WWM_transformers
fp_list_path: ./corpus/CSJ/fp.list