hydra:
  run:
    dir: .

random_seed: 42
n_jobs: 10

corpus_dir: ./corpus/CSJ
out_dir: ./preprocessed_data/CSJ/ver220109_position

# split data
group_list_path: ./corpus/CSJ/core_person_class_by_position_list.txt

# get feature
bert_model_dir: ./bert/Japanese_L-24_H-1024_A-16_E-30_BPE_WWM_transformers
fp_list_path: ./corpus/CSJ/fp.list