hydra:
  run:
    dir: .

random_seed: 42
n_jobs: 8

data:
  batch_size: 32
  num_workers: 4

  in_feat_dir: ./preprocessed_data/CSJ/ver211207_1/infeats
  out_feat_dir: ./preprocessed_data/CSJ/ver211207_1/outfeats

  utt_list: preprocessed_data/CSJ/ver211018_1_cross_val/dev_all_cv4.list

  fp_list: corpus/CSJ/fp_list.txt
    
pred:
  exp_dir: exp/CSJ/ver211018_1_cross_val/weighted_loss/cv4
  out_dir: predicted_data/CSJ/ver211018_1_cross_val/weighted_loss/cv4

  gpus: 1
  auto_select_gpus: True

  checkpoint:
    step: 59999
