hydra:
  run:
    dir: .

random_seed: 42
n_jobs: 8

data:
  batch_size: 32
  num_workers: 4

  data_dir: ./preprocessed_data/ver220310_test
  utt_list: ./preprocessed_data/ver220310_test/utt_morphs.list
  fp_list: ./corpus/CSJ/fp.list
    
pred:
  exp_dir: ./exp/CSJ/ver220110/non_personalized
  out_dir: ./predicted_data/ver220310_test

  gpus: 1
  auto_select_gpus: True

  checkpoint:
    step: 59999
